"""empty message

Revision ID: 6efd13b981a8
Revises: 3406fcf6c241
Create Date: 2019-09-25 22:59:48.232768

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6efd13b981a8'
down_revision = '3406fcf6c241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('hasil_lengkap', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('result', 'hasil')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('hasil', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('result', 'hasil_lengkap')
    # ### end Alembic commands ###
